# Generated by Django 2.1 on 2019-10-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manzanas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mushroomspot',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mushroomspot',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='mushroomspot',
            name='title',
        ),
        migrations.AddField(
            model_name='mushroomspot',
            name='idmz',
            field=models.CharField(default='0000000', editable=False, max_length=15),
        ),
    ]
