# Generated by Django 2.2 on 2019-10-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manzanas', '0004_auto_20191015_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mzscallao',
            options={'managed': False, 'ordering': ('idmz',), 'verbose_name_plural': 'Manzanas'},
        ),
    ]
