# Generated by Django 2.1 on 2019-10-15 15:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0002_auto_20191015_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushroomspot',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
